# Ignore specific rules.
ignore = [
    "T203",
]

# Select all rules.
select = [
    "ALL",
]

# Include specific file types.
extend-include = ["*.ipynb"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".venv",
]

# Line length.
line-length = 79

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

[pydocstyle]
convention = "numpy"

[pycodestyle]
max-doc-length = 79

[pylint]
max-args = 8

[pep8-naming]
classmethod-decorators = ["classmethod", "pydantic.validator"]